# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K7EXnbPgNzQbGUrTvWiFcACc0RjKkYbw
"""

import numpy as np
import matplotlib.pyplot as plt
x = np.random.rand(1000)
plt.hist(x, bins = 20);
plt.show()