# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1boIlPnE5hx-dMDk_JpG2b9lBKtz7AQ7H
"""

#Scatter

import numpy as np
import matplotlib.pyplot as plt

data = np.random.rand(1024, 2)
plt.scatter (data[:,0], data[: ,1])
plt.show(),